services:
  gra-bg-services:
    build:
      context: .
      args:
        - API_GITHUB=${API_GITHUB}
    container_name: gra-bg-services
    restart: unless-stopped
    volumes:
      - ./app:/home/jazzms/app
      - ./filestore:/filestore
    ports:
      - "8888:8000"
    env_file:
      - .env
