version: "3.9"

services:
  gra-mongo:
    image: mongo:latest
    ports:
      - 27037:27017
    volumes:
      - gra-data:/data/db
    restart: unless-stopped
    logging:
      driver: "none"

    networks:
      - gra-net

networks:
    gra-net:
      name: gra-net
      driver: bridge

volumes:
  gra-data:
