version: "3.9"

services:
  # Add other services as needed
  kimera-redis:
    image: redis:latest
    container_name: kimera-redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Expose Redis port
    logging:
      driver: "none"
    networks:
      - kimera-net

  kimera-redisinsight:
    image: redislabs/redisinsight:latest
    container_name: kimera-redisinsight
    ports:
      - "8001:5540"  # Expose RedisInsight UI port
    networks:
      - kimera-net
    depends_on:
      - kimera-redis
    restart: unless-stopped

networks:
    kimera-net:
      name: kimera-net
      driver: bridge