services:
  # Add other services as needed
  gra-redis:
    image: redis:latest
    container_name: gra-redis
    restart: unless-stopped
    ports:
      - "6380:6379"  # Expose Redis port
    logging:
      driver: "none"
    networks:
      - gra-net

networks:
    gra-net:
      name: gra-net
      driver: bridge